/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ClothingStoreGUI;

/**
 *
 * @author annek
 */
public class PanelCustomerProductView extends javax.swing.JPanel {

    /**
     * Creates new form CustomerProductView
     */
    public PanelCustomerProductView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PurposeButtonGroup = new javax.swing.ButtonGroup();
        GenderButtonGroup = new javax.swing.ButtonGroup();
        PurposeLabel = new javax.swing.JLabel();
        GenderLabel = new javax.swing.JLabel();
        CasualButton = new javax.swing.JRadioButton();
        FormalButton = new javax.swing.JRadioButton();
        SportsButton = new javax.swing.JRadioButton();
        SleepButton = new javax.swing.JRadioButton();
        MaleButton = new javax.swing.JRadioButton();
        FemaleButton = new javax.swing.JRadioButton();
        UnisexButton = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ProductList = new javax.swing.JList<>();
        CartButton = new javax.swing.JButton();
        ItemSelectButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(600, 400));

        PurposeLabel.setText("Purpose");

        GenderLabel.setText("Gender");

        PurposeButtonGroup.add(CasualButton);
        CasualButton.setText("Casual");
        CasualButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CasualButtonActionPerformed(evt);
            }
        });

        PurposeButtonGroup.add(FormalButton);
        FormalButton.setText("Formal");

        PurposeButtonGroup.add(SportsButton);
        SportsButton.setText("Sports");

        PurposeButtonGroup.add(SleepButton);
        SleepButton.setText("Sleep");

        GenderButtonGroup.add(MaleButton);
        MaleButton.setText("Male");
        MaleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaleButtonActionPerformed(evt);
            }
        });

        GenderButtonGroup.add(FemaleButton);
        FemaleButton.setText("Female");

        GenderButtonGroup.add(UnisexButton);
        UnisexButton.setText("Unisex");

        ProductList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(ProductList);

        CartButton.setText("View Cart");
        CartButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        CartButton.setOpaque(true);
        CartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CartButtonActionPerformed(evt);
            }
        });

        ItemSelectButton.setText("Select item");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(PurposeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(GenderLabel)
                .addGap(128, 128, 128))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CasualButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FormalButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SportsButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SleepButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(MaleButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FemaleButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(UnisexButton))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addComponent(ItemSelectButton)
                        .addGap(31, 31, 31)
                        .addComponent(CartButton)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PurposeLabel)
                    .addComponent(GenderLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FemaleButton)
                    .addComponent(UnisexButton)
                    .addComponent(MaleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CasualButton)
                    .addComponent(FormalButton)
                    .addComponent(SportsButton)
                    .addComponent(SleepButton))
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CartButton)
                    .addComponent(ItemSelectButton))
                .addContainerGap(79, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CasualButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CasualButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CasualButtonActionPerformed

    private void MaleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaleButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MaleButtonActionPerformed

    private void CartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CartButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CartButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CartButton;
    private javax.swing.JRadioButton CasualButton;
    private javax.swing.JRadioButton FemaleButton;
    private javax.swing.JRadioButton FormalButton;
    private javax.swing.ButtonGroup GenderButtonGroup;
    private javax.swing.JLabel GenderLabel;
    private javax.swing.JButton ItemSelectButton;
    private javax.swing.JRadioButton MaleButton;
    private javax.swing.JList<String> ProductList;
    private javax.swing.ButtonGroup PurposeButtonGroup;
    private javax.swing.JLabel PurposeLabel;
    private javax.swing.JRadioButton SleepButton;
    private javax.swing.JRadioButton SportsButton;
    private javax.swing.JRadioButton UnisexButton;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
