/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ClothingStoreGUI;

/**
 *
 * @author annek
 */
public class PanelCheckout extends javax.swing.JPanel implements InteractivePanel {

    /**
     * Creates new form PanelCheckout
     */
    public PanelCheckout(Controller controller) {
        initComponents();
        initConnections(controller);
    }

    public void initConnections(Controller controller) {
        // CustomerViewButton.addActionListener(e -> controller.customerViewButtonClicked());
        // !! add other connections in here
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Message = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ReciptTable = new javax.swing.JTable();
        TotalPriceLabel = new javax.swing.JLabel();
        Title = new javax.swing.JLabel();
        BackButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(600, 400));

        Message.setText("Thank you for your purchase! Here is a receipt of your order:");

        ReciptTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Size", "Qty", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ReciptTable.getTableHeader().setResizingAllowed(false);
        ReciptTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(ReciptTable);
        if (ReciptTable.getColumnModel().getColumnCount() > 0) {
            ReciptTable.getColumnModel().getColumn(0).setResizable(false);
            ReciptTable.getColumnModel().getColumn(0).setPreferredWidth(300);
            ReciptTable.getColumnModel().getColumn(1).setResizable(false);
            ReciptTable.getColumnModel().getColumn(1).setPreferredWidth(50);
            ReciptTable.getColumnModel().getColumn(2).setPreferredWidth(50);
            ReciptTable.getColumnModel().getColumn(3).setResizable(false);
            ReciptTable.getColumnModel().getColumn(3).setPreferredWidth(50);
        }

        TotalPriceLabel.setText("Total price: $20.00");

        Title.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Title.setText("Checkout");

        BackButton.setText("Back");
        BackButton.setInheritsPopupMenu(true);
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TotalPriceLabel)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Message)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101)
                        .addComponent(Title)))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Title)
                    .addComponent(BackButton))
                .addGap(18, 18, 18)
                .addComponent(Message)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TotalPriceLabel)
                .addContainerGap(127, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BackButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JLabel Message;
    private javax.swing.JTable ReciptTable;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel TotalPriceLabel;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
