/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ClothingStoreGUI.Panels;

import ClothingStoreGUI.Controller;
import ClothingStoreGUI.InteractivePanel;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author annek
 */
public class PanelCart extends javax.swing.JPanel implements InteractivePanel {

    /**
     * Creates new form PanelCart
     */
    public PanelCart(Controller controller) {
        initComponents();
        initConnections(controller);
        ErrorLabel.setVisible(false);
        CartList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
    }

    public void initConnections(Controller controller) {
        BackButton.addActionListener(e -> controller.backButtonClicked());
        ModifyButton.addActionListener(e -> controller.customerModifyButtonClicked());
        RemoveButton.addActionListener(e -> controller.customerRemoveButtonClicked());
        ConfirmButton.addActionListener(e -> controller.customerConfirmButtonClicked());
    }

    public int getSelectedProductIndex() {
        return CartList.getSelectedIndex();
    }

    public JButton getConfirmButton() {
        return ConfirmButton;
    }

    public JButton getModifyButton() {
        return ModifyButton;
    }

    public JButton getRemoveButton() {
        return RemoveButton;
    }
    
    public JLabel getTotalPriceLabel() {
        return TotalPriceLabel;
    }
    
    public void addProductListSelectionListener(ListSelectionListener listener) {
        CartList.addListSelectionListener(listener);
    }
    
    public JLabel getErrorLabel() {
        return ErrorLabel;
    }

    public JList<String> getCartList() {
        return CartList;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.    

     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        CartList = new javax.swing.JList<>();
        ModifyButton = new javax.swing.JButton();
        RemoveButton = new javax.swing.JButton();
        ConfirmButton = new javax.swing.JButton();
        CartLabel = new javax.swing.JLabel();
        ErrorLabel = new javax.swing.JLabel();
        TotalPriceLabel = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(600, 400));

        BackButton.setText("Back");
        BackButton.setInheritsPopupMenu(true);

        CartList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(CartList);

        ModifyButton.setText("Modify item");

        RemoveButton.setText("Remove item");

        ConfirmButton.setText("Confirm purchase");

        CartLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CartLabel.setText("Cart");

        ErrorLabel.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        ErrorLabel.setText("ERROR: Please select a product");

        TotalPriceLabel.setText("Total price: $20.00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TotalPriceLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ErrorLabel)
                        .addGap(61, 61, 61)
                        .addComponent(ConfirmButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(166, 166, 166)
                        .addComponent(CartLabel))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(ModifyButton)
                        .addGap(44, 44, 44)
                        .addComponent(RemoveButton)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BackButton)
                    .addComponent(CartLabel))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ModifyButton)
                    .addComponent(RemoveButton))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(ConfirmButton))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ErrorLabel)
                            .addComponent(TotalPriceLabel))))
                .addContainerGap(71, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JLabel CartLabel;
    private javax.swing.JList<String> CartList;
    private javax.swing.JButton ConfirmButton;
    private javax.swing.JLabel ErrorLabel;
    private javax.swing.JButton ModifyButton;
    private javax.swing.JButton RemoveButton;
    private javax.swing.JLabel TotalPriceLabel;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
