package ClothingStoreGUI.Panels;

import ClothingStoreGUI.Controller;
import ClothingStoreGUI.InteractivePanel;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JSpinner;

/**
 *
 * @author Cam
 */
public class PanelCustomerSelection extends javax.swing.JPanel implements InteractivePanel {

    /**
     * Creates new form PanelCustomerSelection
     */
    public PanelCustomerSelection(Controller controller) {
        initComponents();
        initConnections(controller);
        QtyErrorLabel.setVisible(false);
    }
    
    public void initConnections(Controller controller) {
        BackButton.addActionListener(e -> controller.backButtonClicked());
        AddToCartButton.addActionListener(e -> controller.addToCartButtonClicked());
    }

    public JLabel getProductNameLabel() {
        return ProductNameLabel;
    }

    public JLabel getQtyErrorLabel() {
        return QtyErrorLabel;
    }

    public JSpinner getQtyPicker() {
        return QtyPicker;
    }

    public JComboBox<String> getSizeDropdown() {
        return SizeDropdown;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        ProductNameLabel = new javax.swing.JLabel();
        BackButton = new javax.swing.JButton();
        SizeLabel = new javax.swing.JLabel();
        QtyLabel = new javax.swing.JLabel();
        SizeDropdown = new javax.swing.JComboBox<>();
        QtyPicker = new javax.swing.JSpinner();
        AddToCartButton = new javax.swing.JButton();
        QtyErrorLabel = new javax.swing.JLabel();

        Title.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Title.setText("Customise your order");

        ProductNameLabel.setText("Placeholder product name - $20.00");

        BackButton.setText("Back");
        BackButton.setInheritsPopupMenu(true);

        SizeLabel.setText("Size:");

        QtyLabel.setText("Quantity:");

        SizeDropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        QtyPicker.setName(""); // NOI18N
        QtyPicker.setValue(1);

        AddToCartButton.setText("Add to cart");

        QtyErrorLabel.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        QtyErrorLabel.setText("Error: Please select a valid quantity");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(166, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BackButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(AddToCartButton)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(QtyLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                                    .addComponent(QtyPicker, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(SizeLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(SizeDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Title)
                                .addGap(18, 18, 18)))
                        .addGap(18, 18, 18)
                        .addComponent(QtyErrorLabel))
                    .addComponent(ProductNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addComponent(BackButton)
                .addGap(18, 18, 18)
                .addComponent(Title)
                .addGap(18, 18, 18)
                .addComponent(ProductNameLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SizeLabel)
                    .addComponent(SizeDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(QtyPicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(QtyLabel)
                    .addComponent(QtyErrorLabel))
                .addGap(18, 18, 18)
                .addComponent(AddToCartButton)
                .addContainerGap(105, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddToCartButton;
    private javax.swing.JButton BackButton;
    private javax.swing.JLabel ProductNameLabel;
    private javax.swing.JLabel QtyErrorLabel;
    private javax.swing.JLabel QtyLabel;
    private javax.swing.JSpinner QtyPicker;
    private javax.swing.JComboBox<String> SizeDropdown;
    private javax.swing.JLabel SizeLabel;
    private javax.swing.JLabel Title;
    // End of variables declaration//GEN-END:variables
}
