package ClothingStoreGUI.Panels;

import ClothingStoreGUI.Controller;


public class PanelViewSelection extends javax.swing.JPanel {

    /**
     * Creates new form UserPanel
     */
    public PanelViewSelection(Controller controller) {
        initComponents();
        initConnections(controller);
    }
    
    private void initConnections(Controller controller) {
        CustomerViewButton.addActionListener(e -> controller.customerViewButtonClicked());
        StaffViewButton.addActionListener(e -> controller.staffViewButtonClicked());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        WelcomeMessage = new javax.swing.JLabel();
        CustomerViewButton = new javax.swing.JButton();
        StaffViewButton = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(1200, 800));
        setMinimumSize(new java.awt.Dimension(300, 200));
        setPreferredSize(new java.awt.Dimension(600, 400));

        WelcomeMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WelcomeMessage.setText("Welcome to Object Oriented Outfits, an online shopping website for clothing and footwear.");

        CustomerViewButton.setText("Customer View");
        CustomerViewButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        CustomerViewButton.setMaximumSize(new java.awt.Dimension(100, 25));
        CustomerViewButton.setMinimumSize(new java.awt.Dimension(100, 25));

        StaffViewButton.setText("Staff View");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(WelcomeMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(StaffViewButton, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CustomerViewButton, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(153, Short.MAX_VALUE)
                .addComponent(WelcomeMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CustomerViewButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StaffViewButton))
                .addContainerGap(182, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CustomerViewButton;
    private javax.swing.JButton StaffViewButton;
    private javax.swing.JLabel WelcomeMessage;
    // End of variables declaration//GEN-END:variables
}
